---
minimum_pre_commit_version: 2.4.0
repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        args: [--safe, --quiet]
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.6.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==19.10b0]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending     # Replaces or checks mixed line ending.
        args: [--fix=lf]
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [--remove]
      - id: check-yaml
      - id: debug-statements
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
      - id: flake8
        language_version: python3
        additional_dependencies: [flake8-typing-imports==1.9.0]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.4.0
    hooks:
      - id: reorder-python-imports
        args: ['--application-directories=.:src', --py37-plus]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.2.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770  # NOTE: keep this in sync with setup.py.
    hooks:
      - id: mypy
        files: ^(src/|tests/)
        args: []

  - repo: https://github.com/jazzband/pip-tools
    rev: 5.1.2
    hooks:
      - id: pip-compile
        alias: pip-compile-base
        name: Compile base requirements
        files: ^requirements/base\.(in|txt)$
        args: [requirements/base.in]

  - repo: https://github.com/jazzband/pip-tools
    rev: 5.1.2
    hooks:
      - id: pip-compile
        alias: pip-compile-tests
        name: Compile test requirements
        files: ^requirements/tests\.(in|txt)$
        args: [requirements/tests.in]

  - repo: local
    hooks:
      - id: generate-actions-workflow
        name: Generate Github Actions Workflow
        entry: .github/workflows/templates/generate.py
        pass_filenames: false
        files: '.github/workflows/templates/.*'
        language: script
